#!/usr/bin/env php
<?php

// Ładujemy autoloader i bootstrapa Laravela!
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';

// Bootstrap artisan kernel dla Facades
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

// Teraz możesz korzystać z Artisan, Facade, itp.
use Simplysmart\Simplo\Dbm\Simplo;

$cli = new Simplo();
$cli->run($argv);
