#!/usr/bin/env php
<?php

require getcwd() . '/vendor/autoload.php';

// ⬇️ Załaduj aplikację Laravel
$app = require_once getcwd() . '/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use Simplysmart\Simplo\Simplo;

(new Simplo())->run($argv);

